### ISSUE TITLE
Js-karma help! building test runner for vscode

### ISSUE THREAD

**Issue by Raagh** [segrey/sample-mocha-ts-calc#1]
Hey Sergey, sorry for contacting you directly. I am building a test explorer for vscode for running angular tests, I managed to create a working implementation of loading the tests without running them,  and I know how I would run all the tests together and get the results.

In the current intellij plugin I know you guys have the capability of running specific tests instead of the hole batch, and I was wondering how you guys accomplish that. if you could sent me in the right direction or give me some pointers that would be awesome 👍 .

Again sorry for opening an issue here but the official repository for js-karma is blocked for issues and you didn't had your email on your github profile.

Thanks

**Comment by segrey** [comment]
@Raagh Generally, IntelliJ uses `--grep` to run a specific Karma test:
1. Start karma server with `./node_modules/.bin/ng test`
2. Run `should create the app` test only:
```
$ ./node_modules/karma/bin/karma run -- --grep="should create the app"
```

To be precise, IntelliJ runs a specific Karma test using https://github.com/JetBrains/intellij-plugins/blob/8580eaf89f4f92f70d18675e570ccb1fd212a59e/js-karma/resources/js_reporter/karma-intellij/lib/intellijRunner.js#L87

However, it won't work if `reporters` contain `'kjhtml'` (https://github.com/taras42/karma-jasmine-html-reporter/issues/25). To workaround it, IntelliJ fixes with https://github.com/JetBrains/intellij-plugins/blob/master/js-karma/resources/js_reporter/karma-intellij/lib/kjhtml/intellij-save-specFilter-before-kjhtml.js.

IntelliJ runs a specific Karma test using https://github.com/JetBrains/intellij-plugins/blob/8580eaf89f4f92f70d18675e570ccb1fd212a59e/js-karma/resources/js_reporter/karma-intellij/lib/intellijRunner.js#L87

Hope, it will help.

Please submit questions to https://intellij-support.jetbrains.com/hc/en-us/community/topics/200367229-WebStorm in future, that's a better place to discuss. :)

**Comment by Raagh** [comment]
Awesome, thanks for your help. I will try to do that and if I have any more questions ask them there. 

Again thanks definitely set me in the right direction ahah.

**Comment by Raagh** [comment]
Hey sorry to ask you here again. Could you explain too me this?

  // if testName is undefined, reset jasmine.getEnv().specFilter function
  // otherwise, last specified specFilter will be used
  config.clientArgs = ['--grep=' + (testName || '')];

I am having that exact same problem on windows. I run a set of tests with a fake file with fdescribe init so that every other tests gets skipped but after that if run the tests again all still get skipped even after I deleted the file. Its like its running the same specfilter over and over again.
